# Generated by Django 3.1 on 2021-04-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BROWSE', models.ImageField(upload_to='myimage')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNO', models.IntegerField()),
                ('COURSE', models.CharField(max_length=50)),
                ('SCHOOL', models.CharField(max_length=50)),
                ('YEAR', models.IntegerField()),
                ('PERCENTAGE', models.IntegerField()),
                ('ACTION', models.CharField(max_length=50)),
            ],
        ),
    ]
